name: Lint Code Base

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Super Linter
        uses: github/super-linter@v4
        env:
          RUN_LOCAL: false
          VALIDATE_TERRAFORM: false
